/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    ApiConfig: typeof import('./src/components/ImageGenerator/ApiConfig.vue')['default']
    GenerateButton: typeof import('./src/components/ImageGenerator/GenerateButton.vue')['default']
    GenerationConfig: typeof import('./src/components/ImageGenerator/GenerationConfig.vue')['default']
    GenerationMode: typeof import('./src/components/ImageGenerator/GenerationMode.vue')['default']
    GridColumnsSelector: typeof import('./src/components/GridColumnsSelector.vue')['default']
    ImageGeneratorMain: typeof import('./src/components/ImageGenerator/ImageGeneratorMain.vue')['default']
    ImageGeneratorMainNew: typeof import('./src/components/ImageGenerator/ImageGeneratorMainNew.vue')['default']
    ImageUpload: typeof import('./src/components/ImageGenerator/ImageUpload.vue')['default']
    PromptInput: typeof import('./src/components/ImageGenerator/PromptInput.vue')['default']
    ResultDisplay: typeof import('./src/components/ImageGenerator/ResultDisplay.vue')['default']
  }
}
