/**
 * Cloudflare Snippet / Worker for Market Random Image API
 *
 * Compliant with: https://developers.cloudflare.com/rules/snippets/
 *
 * Features:
 * - GET /api/market-random - Get a random emoji image from all groups
 * - GET /api/market-random?group=GROUP_ID - Get a random emoji from specific group
 * - GET /api/market-random?redirect=true - Redirect to the image URL
 */

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type'
}

// Inlined Group IDs to avoid extra fetch (Snippet Limitation - only 1 async continuation allowed)
// Auto-generated by update-market-metadata.js
const MANIFEST_GROUPS = [
  'group-1755833820210',
  'group-1755865026150',
  'group-1755913811947',
  'group-1755913842696',
  'group-1755913884262',
  'group-1755913887877',
  'group-1755964482153',
  'group-1755966299851',
  'group-1755968404073',
  'group-1755970088527',
  'group-1756869834619',
  'group-1756869864620',
  'group-1756869887449',
  'group-1756869988533',
  'group-1756870014160',
  'group-1756870039233',
  'group-1756870069420',
  'group-1756870080244',
  'group-1756871007943',
  'group-1757396353003',
  'group-1758072938224',
  'group-1758073408523',
  'group-1758290078442',
  'group-1758291025412',
  'group-1758292062046',
  'group-1758294156025',
  'group-1758296437858',
  'group-1758435118749',
  'group-1758505345831',
  'group-1758703744073',
  'group-1758704054933',
  'group-1758720673759',
  'group-1759062077224',
  'group-1759064721561',
  'group-1759065160041',
  'group-1759065232486',
  'group-1759671340288',
  'group-1759672893426',
  'group-1759674514752',
  'group-1759676376056',
  'group-1759678713445',
  'group-1759820121581',
  'group-1759820228329',
  'group-1760528644701',
  'group-1760528756665',
  'group-1760717207846',
  'group-1761060574614',
  'group-1761152742132',
  'group-1761153964258',
  'group-1761154281184',
  'group-1761154861189',
  'group-1761155486316',
  'group-1761182392763',
  'group-1761182584049',
  'group-1761182716118',
  'group-1761182869790',
  'group-1761182921332',
  'group-1761327403281',
  'group-1761328497264',
  'group-1761442802743',
  'group-1761445939845',
  'group-1761446423721',
  'group-1761446644760',
  'group-1761563222611',
  'group-1761569266491',
  'group-1761569314695',
  'group-1761572596776',
  'group-1761749438138',
  'group-1761910351243',
  'group-1762174377236',
  'group-1762250814892',
  'group-1762354787132',
  'group-1762354829964',
  'group-1762519966926',
  'group-1762523521486',
  'group-1762524245454',
  'group-1762692296711',
  'group-1762695828124',
  'group-1762696295842',
  'group-1762696672054',
  'group-1762778187463',
  'group-1762816988844',
  'group-1762945443494',
  'group-1763015750148',
  'group-1763038870366',
  'group-1763193137015',
  'group-1763199195538',
  'group-1763199932836',
  'group-1763270508379',
  'group-1763303057469',
  'group-1763969927132',
  'group-1764340960340',
  'group-1764386468076',
  'group-1764592283419',
  'group-1764738272674',
  'group-1764980488364',
  'group-1765008889810',
  'group-1765284902642',
  'group-1765462664131',
  'group-1765771538157',
  'group-1765806805581',
  'group-1765895444745',
  'group-1765972558970',
  'group-1765973308075',
  'group-1765973766413',
  'group-1765974153699',
  'group-1765977432564',
  'group-1766196297035',
  'group-1766412592583',
  'group-1766479646538',
  'group-1766486669577',
  'group-1766586968469',
  'group-1766638440016',
  'group-1766734481816',
  'group-1766763084048',
  'group-1766845450023',
  'group-1766849153193',
  'group-1766906735649',
  'group-1766933725176',
  'group-1766980740966',
  'group-1766985490123',
  'group-1766995179445',
  'group-1767006142804',
  'group-1767080865612',
  'group-1767093036745',
  'group-1767100685975',
  'group-1767152000501',
  'group-1767197875251',
  'group-1767256080865',
  'group-1767274356197',
  'group-1767312211071',
  'group-1767342425318',
  'group-1767368298347',
  'group-1767431500452',
  'group-1767453793359',
  'group-1767629262989',
  'group-1767644169911',
  'group-1767644173882',
  'group-1767644230006',
  'group-1767644234348',
  'group-1767644238830',
  'group-1767644351306',
  'group-1767644414780',
  'group-1767644422683',
  'group-1767644477951',
  'group-1767644481428',
  'group-1767644542108',
  'group-1767644605229',
  'group-1767644662750',
  'group-1767644666485',
  'group-1767644842489',
  'group-1767644847774',
  'group-1767644906904',
  'group-1767645020723',
  'group-1767645029605',
  'group-1767645142807',
  'group-1767645208165',
  'group-1767645265317',
  'group-1767645270562',
  'group-1767645277428',
  'group-1767645336767',
  'group-1767645385314',
  'group-1767645395060',
  'group-1767645449104',
  'group-1767645457405',
  'group-1767645462518',
  'group-1767645514114',
  'group-1767645575781',
  'group-1767645584240',
  'group-1767682512237',
  'group-1767684284025',
  'group-1767772291605',
  'group-1767818283816',
  'group-1767967939351',
  'group-1768045118897',
  'group-1768393531015',
  'group-1768553733361',
  'group-1768707060171',
  'group-1768722447397',
  'group-1768743503137',
  'group-1768835894932',
  'group-1768836202969',
  'group-1768974056814',
  'group-1768985215189',
  'group-1768998692628',
  'group-1769002748394',
  'group-1769003966293',
  'group-1769047520075',
  'group-1769047707353',
  'group-1769217168177',
  'group-1769340256221',
  'group-1769348522883',
  'group-1769437619842',
  'group-1769597270429',
  'group-1769701317520',
  'group-1770011593793',
  'group-1770377514670',
  'group-1770993590742',
  'group-1770994227890',
  'group-1770994649248',
  'group-1770995032971',
  'group-1770995462064',
  'group-1770995929990',
  'group-1770996268047',
  'group-1770996603720',
  'group-1770997107993',
  'group-1771678156755',
  'group-1771683613371',
  'telegram_1767489608603_al7dd5dso',
  'telegram_1767668782654_xq4p6dziy',
  'telegram_1768051202527_nuh93wcz6',
  'telegram_1768060176202_s2vrjm6u2',
  'telegram_1768060557672_omrisx7d1',
  'telegram_1768095637590_xydw7ixxo',
  'telegram_1768723757505_9z7ul5ipe',
  'telegram_1768740682292_ectw51493',
  'telegram_1768784920309_bi3zjb0ga',
  'telegram_1768785247194_ge55trbbi',
  'telegram_1768785349722_vnhikxv7c',
  'telegram_1768785476294_3u1yi30cl',
  'telegram_1768785560498_yodj04872',
  'telegram_1768785939238_j15zbg1a8',
  'telegram_1768786165292_zk58pe8i4',
  'telegram_1768786280727_rlvadpydq',
  'telegram_1768787332652_kgn5kmid0',
  'telegram_1768789010285_kqetakqsg',
  'telegram_1768789739460_3byt04i4d',
  'telegram_1768789754173_ja2c0nmq1',
  'telegram_1768793747428_99hnvqyuo',
  'telegram_1768793767022_1liuj775f',
  'telegram_1768794024606_h3j4sspav',
  'telegram_1768794247420_lvtfpx5zf',
  'telegram_1768794383184_e06vx9z31',
  'telegram_1768992916429_97sykhxm6',
  'telegram_1769219920577_b6mx8tuo8',
  'telegram_1769227166276_pe3zr005t',
  'telegram_1769509754660_7kmjqdidx',
  'telegram_1769510887234_5q2fpkv3z',
  'telegram_1769511180822_zqmwic02u',
  'telegram_1769511474384_envex0bjj',
  'telegram_1769511573956_2w11el2v2',
  'telegram_1769511769452_ks9dkq7hz',
  'telegram_1769511856433_rs312yb29',
  'telegram_1769512151296_q022kmtjq',
  'telegram_1769512256842_663azc5u8',
  'telegram_1769512344416_k2hdljk2a',
  'telegram_1769615017556_kmruozok9',
  'telegram_1769615581494_gqc9xpehp',
  'telegram_1770339362573_6txoyq4pg',
  'telegram_1770379338933_md4h8c5u5',
  'ungrouped'
]

// Helper function to get random item from array
function getRandomItem(array) {
  if (array.length === 0) return null
  return array[Math.floor(Math.random() * array.length)]
}

export default {
  async fetch(request) {
    // Handle CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders })
    }

    if (request.method !== 'GET') {
      return new Response('Method Not Allowed', { status: 405, headers: corsHeaders })
    }

    try {
      // Parse query parameters
      const url = new URL(request.url)

      const groupId = url.searchParams.get('group')
      const redirectParam = url.searchParams.get('redirect')
      const shouldRedirect = redirectParam === 'true' || redirectParam === '1'

      // Filter by group ID if specified, otherwise use all groups
      let targetGroups = MANIFEST_GROUPS.filter(id => id !== 'favorites' && id !== 'buffer')

      if (groupId) {
        if (!targetGroups.includes(groupId)) {
          return new Response(JSON.stringify({ error: 'Group not found' }), {
            status: 404,
            headers: { ...corsHeaders, 'Content-Type': 'application/json; charset=UTF-8' }
          })
        }
        targetGroups = [groupId]
      }

      if (targetGroups.length === 0) {
        return new Response(JSON.stringify({ error: 'No groups available' }), {
          status: 404,
          headers: { ...corsHeaders, 'Content-Type': 'application/json; charset=UTF-8' }
        })
      }

      // Randomly select ONE group from the list
      const selectedGroupId = getRandomItem(targetGroups)

      if (!selectedGroupId) {
        return new Response(JSON.stringify({ error: 'No group selected' }), {
          status: 404,
          headers: { ...corsHeaders, 'Content-Type': 'application/json; charset=UTF-8' }
        })
      }

      // Single fetch + json parse chained (only 1 async continuation point)
      const groupUrl = new URL(`/assets/market/group-${selectedGroupId}.json`, url.origin)
      const groupData = await fetch(groupUrl.toString()).then(r => {
        if (!r.ok) throw new Error(`Failed to load group data: ${r.status}`)
        return r.json()
      })

      if (!groupData.emojis || groupData.emojis.length === 0) {
        return new Response(JSON.stringify({ error: 'No emojis in selected group' }), {
          status: 404,
          headers: { ...corsHeaders, 'Content-Type': 'application/json; charset=UTF-8' }
        })
      }

      // Select random emoji from the group
      const randomEmoji = getRandomItem(groupData.emojis)

      if (!randomEmoji) {
        return new Response(JSON.stringify({ error: 'Failed to select random emoji' }), {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json; charset=UTF-8' }
        })
      }

      // Handle Redirect
      if (shouldRedirect) {
        return Response.redirect(randomEmoji.url, 302)
      }

      // Return JSON
      return new Response(JSON.stringify(randomEmoji, null, 2), {
        status: 200,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json; charset=UTF-8',
          'Cache-Control': 'no-cache, no-store, must-revalidate'
        }
      })
    } catch (error) {
      console.error('[MarketRandom] Error:', error)
      return new Response(
        JSON.stringify({ error: 'Internal Server Error', details: String(error) }),
        {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json; charset=UTF-8' }
        }
      )
    }
  }
}
